export const APP_LOAD = '@@app/LOAD'
export const APP_ASYNC_START = '@@app/ASYNC_START'
export const APP_ASYNC_END = '@@app/ASYNC_END'
export const APP_REDIRECT_LOCATION = '@@app/REDIRECT_LOCATION'

export const SET_VIEW_TAB = '@@app/SET_VIEW_TAB'
export const SET_VIEW_PAGE_ = '@@app/SET_VIEW_PAGE_'
export const SET_TAG_FILTER = '@@app/SET_TAG_FILTER'
export const SET_MEDIUM_FILTER = '@@app/SET_MEDIUM_FILTER'

export const SEARCH_FORM_LOADED = '@@search/FORM_LOADED'
export const SEARCH_FIELD_UPDATE = '@@search/FIELD_UPDATE'
export const SEARCH_QUERY_SUBMITTED = '@@search/QUERY_SUBMITTED'
export const SEARCH_FORM_UNLOADED = '@@search/FORM_UNLOADED'

export const HOME_PAGE_LOADED = '@@home/PAGE_LOADED'
export const HOME_PAGE_UNLOADED = '@@home/PAGE_UNLOADED'

export const LOGIN_FORM_LOADED = '@@login/FORM_LOADED'
export const LOGIN_FORM_UNLOADED = '@@login/FORM_UNLOADED'

export const REGISTER_FORM_LOADED = '@@register/FORM_LOADED'
export const REGISTER_FORM_UNLOADED = '@@register/FORM_UNLOADED'

export const PROFILE_PAGE_LOADED = '@@profile/PAGE_LOADED'
export const PROFILE_PAGE_UNLOADED = '@@profile/PAGE_UNLOADED'
export const PROFILE_FAVORITES_LOADED = '@@profile/FAVORITES_LOADED'
export const PROFILE_FAVORITES_UNLOADED = '@@profile/FAVORITES_UNLOADED'
export const PROFILE_FOLLOW_USER = '@@profile/FOLLOW_USER'
export const PROFILE_UNFOLLOW_USER = '@@profile/UNFOLLOW_USER'

export const POST_ITEM_LOADED = '@@post/ITEM_LOADED'
export const POST_ITEM_UNLOADED = '@@post/ITEM_UNLOADED'
export const POST_ITEM_FAVORITED = '@@post/ITEM_FAVORITED'
export const POST_ITEM_UNFAVORITED = '@@post/ITEM_UNFAVORITED'
export const POST_ITEM_ADD_COMMENT = '@@post/ITEM_ADD_COMMENT'
export const POST_ITEM_DELETE_COMMENT = '@@post/ITEM_DELETE_COMMENT'
export const POST_ITEM_DELETE_POST = '@@post/ITEM_DELETE_POST'
export const POST_ITEM_DELETE_UPLOAD = '@@post/ITEM_DELETE_UPLOAD'

export const MODAL_ITEM_LOADED = '@@modal/ITEM_LOADED'
export const MODAL_ITEM_UNLOADED = '@@modal/ITEM_UNLOADED'
export const MODAL_ITEM_REDIRECT = '@@modal/ITEM_REDIRECT'

export const EDITOR_FORM_LOADED = '@@editor/FORM_LOADED'
export const EDITOR_FORM_UNLOADED = '@@editor/FORM_UNLOADED'
export const EDITOR_TAG_ADDED = '@@editor/TAG_ADDED_TO_POST'
export const EDITOR_TAG_REMOVED = '@@editor/TAG_REMOVED_FROM POST'
export const EDITOR_TEXT_FIELD_UPDATE = '@@editor/TEXT_FIELD_UPDATE'
export const EDITOR_CHECKBOX_SWITCHED = '@@editor/CHECKBOX_SWITCHED'
export const EDITOR_POST_SUBMITTED = '@@editor/POST_SUBMITTED'
export const EDITOR_TITILE_UPDATE = '@@editor/EDITOR_TITILE_UPDATE'

export const TOASTIFY = '@@TOASTIFY'

export const DROPZONE_ACTION = '@@dropzone/ACTIVATING_DROPZONE'
export const DROPZONE_INACTIVE = '@@dropzone/DEACTIVATING_DROPZONE'
export const DROPZONE_INPUT_ZONE_LOADED = '@@dropzone/INPUT_ZONE_LOADED'
export const DROPZONE_MEDIA_PROGRESS = '@@dropzone/CURRENT_UPLOAD_PROGRESS'
export const DROPZONE_ITEMS_FETCHED = '@@dropzone/ITEMS_FETCHED'
export const DROPZONE_MEDIA_DELETED = '@@dropzone/DELETE_UPLOAD'
export const DROPZONE_MEDIA_UPLOADED = '@@dropzone/MEDIA_UPLOADED'
export const DROPZONE_FORM_ITEMS_UNLOADED = '@@dropzone/FORM_ITEMS_UNLOADED'

export const SETTINGS_FORM_SAVED = '@@settings/FORM_SAVED'
export const SETTINGS_FORM_LOADED = '@@settings/FORM_LOADED'
export const SETTINGS_FORM_UNLOADED = '@@settings/FORM_UNLOADED'

export const AUTH_USER_LOGIN = '@@auth/USER_LOGIN'
export const AUTH_USER_LOGOUT = '@@auth/USER_LOGOUT'
export const AUTH_USER_REGISTER = '@@auth/USER_REGISTER'
export const AUTH_USER_DELETE = '@@auth/USER_DELETE'
export const AUTH_UPDATE_FIELD = '@@auth/UPDATE_FIELD'

export const TOAST_SUCCESS_NOTIFICATION = '@@toast/NOTIFY_SUCCESS'
export const TOAST_INFO_NOTIFICATION = '@@toast/NOTIFY_INFO'
export const TOAST_ERROR_NOTIFICATION = '@@toast/NOTIFY_ERROR'